### ISSUE TITLE
Clip, Threshold, Select Functors

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#17]
It would be nice to have a functors such as
- `clip(min, max)` (values `<min` are mapped to min, values `>max` are mapped to max)
- `select(min, max)` (values `<min` or `>max` are assigned "no value"/kept transparent)
- `threshold([<|<=|>=|>], value)`

The can be useful when visualizing small detail areas with color bars just focusing on a small fluctuation in a much larger field.

**Comment by theZiz** [comment]
I thought about your suggestion, but as new functors are expensive (atm you use most of the time 5 functors; with a chain length of 3 you have 500 prebuilt chains. With 6 functors you already get 864 different chains - nearly doubled compilation time) and as the behaviour can be implemented with the already existing solution I will not add the proposed functors.

* The `clip(min, max)` behaviour is already implemented for the transfer function, but you have to transform the domain [min;max] to [0,1]
* To not show regions like with your proposed `select(min, max)` just mark the representing area in the transfer function with no opacity.
* Same for `threshold`. Use the functor chain to move the interesting part of your data to the domain 0..1 to select and deselect data with the transfer function, e.g. with a square edge ( ___|‾‾‾|__|‾ )
