### ISSUE TITLE
Mention CMAKE_INSTALL_PREFIX in INSTALL.md

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/isaac#171]
Perhaps one should mention the use of of `-DCMAKE_INSTALL_PREFIX=/your/path` in the ISAAC install already. Otherwise, a system-wide installation is attempted. 
https://github.com/ComputationalRadiationPhysics/isaac/blob/dev/INSTALL.md#installing-the-library

**Comment by psychocoderHPC** [comment]
This is basic CMake knowledge. I would avoid mentioning it because ISAAC is not CMake documentation.
The system-wide installation will fail anyway if you do not install with root rights, which is generally a bad idea.

**Comment by PrometheusPi** [comment]
I am fine with that and will close the issue
