### ISSUE TITLE
Textbased MetaDataConnector implementation

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/isaac#19]
It would be awesome and quite handy to be able to connect via telnet or similar to the isaac server and to send and receive data with a text based interface. However nobody wants to enter JSON themself, so the most common messages should be easier to send like this
```
> list⏎
Simulation A, 12 Nodes, 512x512x512
Simulation B, 42 Nodes, 1024x1024x128
> observe "Simulation A"⏎
{
    "metadata": {
        "currentStep": 2342
    }
}
{
    "metadata": {
        "currentStep": 2343
    }
}
> metadata "Simulation A" "pause" true⏎
```
Furthermore recevied JSON packages should be still JSON, but formated e.g with indentation.

**Comment by theZiz** [comment]
This is somewhat done with Iltis: https://github.com/ComputationalRadiationPhysics/iltis

However you can also now connect to the server with telnet, but have to answer everything yourself. ;)

**Comment by ax3l** [comment]
png to ascii art conversion on telnet!
`telnet towel.blinkenlights.nl`
