### ISSUE TITLE
LWS: CMake File

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#31]
(just to document our offline results)
Building against libwebsockets (LWS) 1.7.4 leads to a missing `libwebsockets-1.7.4/lib/cmake/libwebsockets/LibwebsocketsTargets.cmake` file which is not installed by LWS' `make install` as in previous releases.

This might be an upstream bug or us using the wrong file (should we use `LibwebsocketsConfig.cmake` instead?)

**Comment by ax3l** [comment]
That file was [intentionally removed](https://github.com/warmcat/libwebsockets/issues/279), but someone complains, too: 3ae1badae7a05e0982e0dfbcb078da3d4b92a81d#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by theZiz** [comment]
Thanks for the investigation! Will have a look at this.

**Comment by theZiz** [comment]
Fixed in libwebsockerts upstream

**Comment by ax3l** [comment]
When, where? Can't find a fix in their `master`.

**Comment by theZiz** [comment]
https://github.com/warmcat/libwebsockets/commit/88d118d6705f0cb5bb8f5e6c817cb051ee87dbf6

**Comment by ax3l** [comment]
excellent, thx!
