### ISSUE TITLE
GCC 4.9.2: Missing Initializer Clipping Member

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#32]
With gcc 4.9.2 on hypnos (HZDR) I get the following warning during build of PIConGPU:

```
src/picongpu/include/plugins/IsaacPlugin.hpp:386:1561:   required from here
src/isaac/insitu/isaac.hpp:378:567:
  warning: missing initializer for member ‘isaac::clipping_struct::elem’
  [-Wmissing-field-initializers] TScale scale
```

isaac version: 7e64d00dbfffc30c157ad17626d2a00f994ccc56
PIConGPU version: https://github.com/theZiz/picongpu/commit/70c0593ac00a58db88fca3b6fcf72aeadf1660f6

(Not sure if this is actually in the PIConGPU repo/branch I linked.)

**Comment by theZiz** [comment]
Fixed: https://github.com/ComputationalRadiationPhysics/isaac/commit/f586b6e2677d98698c5b6986a2dcc8f2acfa77dc Will be merged with master soon™.
