### ISSUE TITLE
Functor Chain: Data Source

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#34]
Is it possible to have the data source itself, currently at the beginning of the functor chain, being included *inside* the functor chain?

E.g., `idem(DensityElectrons) | add(DensityProtons)`

**Comment by theZiz** [comment]
Atm: No.
In the future: Let's discuss ;)

**Comment by theZiz** [comment]
As the question is answered, but not discussion started: Close

**Comment by ax3l** [comment]
did not discussion because it is cristal clear that this would be an awesome feature!

[curl(E,B)](https://en.wikipedia.org/wiki/Poynting_vector) for example
