### ISSUE TITLE
Fix license headers

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/isaac#35]
The license headers mention the "GNU General Lesser Public License" in the last paragraph which has the 2nd and 3rd word swapped.

**Comment by theZiz** [comment]
Interesting, in fact I just gutenberged it from the GPL site. O_o

**Comment by Flamefire** [comment]
The GPL site (AFAIK) only provides the GPL license and asks you to insert "Lesser" before "General" at all 3 places if you want the LGPL.

PS: "gutenberged" :laughing:

**Comment by theZiz** [comment]
Finally fixed it, thanks for the notice: https://github.com/ComputationalRadiationPhysics/isaac/commit/615340cf3d09b14b71d2c7f3312db80b42da9f23
