### ISSUE TITLE
Example renderings wrongly named

### ISSUE THREAD

**Issue by bussmann** [ComputationalRadiationPhysics/isaac#37]
Kelvin-Helmholtz not Kevin!

**Comment by theZiz** [comment]
Really? Again? >.<

**Comment by bussmann** [comment]
No more 'Home alone' for you!

**Comment by theZiz** [comment]
One or two days before my thesis submission 50% of all the Kelvins were still Kevins... So this error is not new *cough*. However fixed: https://github.com/ComputationalRadiationPhysics/isaac/commit/3204bd82413b1835302e719ebc2878b44f6eca0b

**Comment by bussmann** [comment]
http://de.uncyclopedia.wikia.com/wiki/Kevinismus

**Comment by theZiz** [comment]
My berlin past catches up with me... 18 years Lichtenberg close to Marzahn **had** to leave traces!
