### ISSUE TITLE
ISAAC logo not animated when stream is offline

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/isaac#38]
It's a GIF, so why doesn't it move??!!

**Comment by theZiz** [comment]
First of all we need to discuss, whether it is pronounced "GIF" or "JIF". Depending on your answer I will think about solving this issue.

**Comment by slizzered** [comment]
I'm far into the "GIF" corner. Similar how you would pronounce "GIT" (not "JIT")

**Comment by theZiz** [comment]
Good answer. I will think about your problem.

**Comment by theZiz** [comment]
![Aint nobody got time for that](http://ziz.gp2x.de/stuff/notime.jpg "Aint nobody got time for that")
