### ISSUE TITLE
race condition if pthread is used

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/isaac#49]
If isaac is used with threading enabled the marked lines can result in a racecondition.
https://github.com/ComputationalRadiationPhysics/isaac/blob/dev/lib/isaac.hpp#L1674-L1675

If the master thread is reading or manipulation the json object while the thread is deleting the old and creates a new one.

**Comment by theZiz** [comment]
![Orly?](http://ziz.gp2x.de/stuff/orly.jpg "Orly?")

Thought I fixed this:
5d42f8ed6f330c2804d62b108fde5dd8ca5d1e6d

This could only happen atm, if the user keeps the `json_t*` object return by `getJsonMetaRoot()` instead of recalling the function every time (as it is meant to be).

**Comment by psychocoderHPC** [comment]
OK thx, this was hidden for me because of the direct push to the dev branch.

**Comment by psychocoderHPC** [comment]
fixed with 5d42f8e
