### ISSUE TITLE
Clipping planes

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/isaac#5]
The goal is to have some kind of free defineable (no need to be axis orthogonal!) number of clipping planes for a better view of inner events.

**Comment by theZiz** [comment]
Done: https://github.com/ComputationalRadiationPhysics/isaac/commit/d759605d2fce8f4edcbdd484ccb568df764d0126

**Comment by ax3l** [comment]
excellent! :cherry_blossom:

**Comment by bussmann** [comment]
u r awesome
