### ISSUE TITLE
CMake: -march/mtune=native

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#52]
`add_definitions` such as `-march=native -mtune=native` should not be set manually but controlled by CMake host and cross-compile chains.

I disabled those to get rid of compile issues on AWS.

**Comment by theZiz** [comment]
Yes. I noticed just yesterday that I set some very dubious settings int the CMake-config-file.

Thanks for issuing this and forcing me to fix this. ;)

**Comment by ax3l** [comment]
actually the same with your `C++11` switch ;)

just set the `CXX_STANDARD` ;)

**Comment by theZiz** [comment]
Yeah, I am locking over the config file right now and consider, how I solve this the best way. CXX_STANDARD probably is the best way as e.g. `nvcc` has a big problem with `-std=c++11` defined twice. O_o

**Comment by ax3l** [comment]
yes, also use CMake 3.3+ since that fixes exactly that problem.

**Comment by theZiz** [comment]
I wonder, whether ISAAC should not change the CXX_STANDARD at all. What if ISAAC is the only C++11 library used by some application, but fails to find some dependency. In that case ISAAC would have set the standard to C++11 although the find_package(ISAAC) fails.

In that case it would make sense to add `-std=c++11` to ISAAC_DEFINITIONS, but as mentioned before: This fucks up the nvcc. AAAARGH!

**Comment by theZiz** [comment]
Hopefully fixed this: https://github.com/ComputationalRadiationPhysics/isaac/commit/d7a1a7b631afcb01f1ec8ea460ddf765017efc32
Because of the reason mentioned above I do not set C++11 anymore, but check for it and warn the user if (s)he wants to use ISAAC without C++11.
