### ISSUE TITLE
Server Ports: Specify Device

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#53]
It would be great if the isaac **server** could optionally specify the *device* to open the listening ports on.

Currently, a `--web_port 1234` it is listening on all devices, I would make the long syntax of that `--web_port *:1234`. (If nothing is specified, implicitly `*:` or `localhost:` should be assumed).

**Comment by theZiz** [comment]
I added explicit options for the interfaces of every of the three server bindings. https://github.com/ComputationalRadiationPhysics/isaac/commit/dce35b462497d5bb61c68eb4d7ebbf8cf82a68dc

So instead of `--web_port lo:1234` you can use `--web_port 1234 --web_int lo` to only listen on localhost for the websocket connection.

**Comment by ax3l** [comment]
thanks for the quick update! :sparkles: 

oh, that's what `int` means. wouldn't `dev` be clearer since it is a less overloaded abbreviation?

too bad `dev:port` did not make it as its syntax :'(

**Comment by theZiz** [comment]
The syntax has no advantage, just more work for a very rarely used feature ;)

Hm, `dev` looks nicer indeed, but device is not as correct as interface is, as many interfaces are no real devices (like vpn or lo). In the end I just don't like too long command line parameters. ^^'

Btw. for now ipv6 works only with `*`, you can't bind an interface with ipv6. However I prepared my code, that it it easy and fast to implement in the future, so if you need it, don't hesitate to tell (but only if you really need ipv6 :>)

**Comment by ax3l** [comment]
Yeah its not important, just my suggestion from year long apache, ssh, etc. syntax I am used to.
