### ISSUE TITLE
HTML Client: Init Bounding Box Zoom Level

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#54]
When connecting to an already running simulation with a second HTML client, the initial zoom level of the bounding box is not set until one sets a zoom level again.

Found with `interface_presentation.htm` in current dev as of de324423fe29b382549b94dfc549e2d6c3c70edb

**Comment by theZiz** [comment]
Fixed: https://github.com/ComputationalRadiationPhysics/isaac/commit/031d429f1ac388f0bccf78a9af347f008485518a
