### ISSUE TITLE
Install Process

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#55]
Please let us finish the implementation of the install process so that a make install really installs the library in a sane way (copies the required headers).

It's fine that the `server` is build at `make`, too. It can then be simply copied to `CMAKE_INSTALL_PREFIX/bin/` alongside the library.

**Comment by theZiz** [comment]
Done: https://github.com/ComputationalRadiationPhysics/isaac/commit/f3d2890a579b02466a463b07504d805a8a00e526
