### ISSUE TITLE
Install Docs: Non-Default Options

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#56]
The current install docs for, e.g., libwebsockets do not tell an unexperienced user that either third party dependencies such as OpenSSL & zlib are required to be installed or can simply be disabled because we won't use them (yet) anyway.

Please add the CMake flags such as [`-LWS_WITH_SSL=OFF`](https://github.com/warmcat/libwebsockets/blob/82dc6313d104cc152c6c5be2a341fc7394903740/CMakeLists.txt#L71) in the `libwebsockets` section to your `INSTALL.md` so users can smoothly go along via copy-&-paste install. You can also document your options to e.g. disable `gstreamer` via `-ISAAC_GST=OFF` directly there, too. Don't let the users search for that, not all have `ccmake` installed.

**Comment by theZiz** [comment]
Well, maybe I should just add `ccmake` to the dependencies for ISAAC. ;)

jk, will have a look at this.

**Comment by theZiz** [comment]
Fixed: https://github.com/ComputationalRadiationPhysics/isaac/commit/e6ea6defa4c92adc2fd73d07a8c2ba5d8200a18f
