### ISSUE TITLE
Server: libwebsockets 2.1.1+

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/isaac#63]
Due to a nasty connection endless loop on connect to isaac's web port, we should require libwebsockets
- 2.1.1+
or
- 2.2.1+

both 2.1.0, 2.2.0 and earlier versions have the bug

**Comment by theZiz** [comment]
Wait, did we really check 2.2.0? I thought only 2.1.0?

**Comment by ax3l** [comment]
We checked 2.2.1 and 2.1.1 and both worked

**Comment by theZiz** [comment]
Well, we guessed in the blue, which commit resulted in the shown buggy behaviour. I will just test version 2.2.0 ;)

**Comment by theZiz** [comment]
Eeyup, every version beginning with 2.1.1 is working ;)
Proven by testing!

**Comment by theZiz** [comment]
Done: https://github.com/ComputationalRadiationPhysics/isaac/commit/4ccd63f798f8aa8c693652dc59215b81aa6a036a

**Comment by ax3l** [comment]
but... did you test it in a docker container? a naïve execution did not show the error in the first place ;)

**Comment by theZiz** [comment]
No, because being in a docker container was not the fault in the first place. It was just coincidence, that you put a non working version in the container. ;)

**Comment by ax3l** [comment]
but the non-working version was a *working* version outside the container. so your wild guess that 2.2.0 is working without testing it in a docker container is *unacceptable* !!!1111elf

**Comment by theZiz** [comment]
Well, fortunately is does not need to be accepted by your standards to get this issue closed. :> But feel free to retest version 2.2.0 in a docker container. :P
