### ISSUE TITLE
Examples: Install Targets

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#65]
Just for convenience, can you please add the two generated binaries `example_alpaka` and `example_cuda` as an install target in the `example/`'s `CMakeLists.txt`?

(to allow `make install`)

**Comment by ax3l** [comment]
p.s. maybe we can also give the binaries also a more specific name

**Comment by theZiz** [comment]
So many wishes...

**Comment by theZiz** [comment]
Done: https://github.com/ComputationalRadiationPhysics/isaac/commit/2b24f0bc965381ce3f852199e30983c962eb3f44
