### ISSUE TITLE
ISAACConfig.cmake: ISAAC_DIR

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#68]
The location of CMake's [`ISAAC_DIR`](https://github.com/ComputationalRadiationPhysics/isaac/blob/b0aedd368a6c42612668fae5d5d49f3e907db5d1/lib/ISAACConfig.cmake#L22-L23) is currently badly placed.

If for example only the `CMAKE_PREFIX_PATH` is set as a hint, this script sets to the `ISAAC_DIR` to the place of the `*Config.cmake` file itself (`<prefix>/lib/CMake/ISAAC/`) instead of the install root `<prefix>/`. This causes all dependent vars, e.g. include paths, to be wrong.

I would recommend to move the `*Config.cmake` files even in the repo to `lib/cmake/ISAAC/` and fix the path it sets.

Affects the latest release, 1.3.1-1.3.3

**Comment by theZiz** [comment]
I don't really get, what you mean or want. From which "script" are you speaking? I also don't get, why the in source position of the `IsaacConfig*.cmake` files is a problem.

**Comment by ax3l** [comment]
> From which "script" are you speaking?

`ISAACConfig.cmake`

> I also don't get, why the in source position of the IsaacConfig*.cmake files is a problem.

If you install the ISAAC lib and export `CMAKE_PREFIX_PATH` to its install root, than the CMake variable `ISAAC_DIR` will not point to the prefix but to `<prefix>/lib/cmake/ISAAC/`. That is wrong.

**Comment by ax3l** [comment]
fixed with  #74
