### ISSUE TITLE
Replace __CUDACC_VER__

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#69]
`__CUDACC_VER__` is deprecated in CUDA 9.0 (and already heavily broken in the release candidate 2, CUDA 9.0.103).

Use `__CUDACC_VER_MAJOR/MINOR/BUILD__` instead.

Used at least in `isaac.hpp`

**Comment by theZiz** [comment]
I really wonder, what is so hard on defining
```C++
#define __CUDACC_VER_  (__CUDACC_VER_MAJOR__ * 10000 + __CUDACC_VER_MINOR__ * 100 + __CUDACC_VER_BUILD__)
```
for the CUDA headers.
Just saying...

Anyway: [Fixed](https://github.com/ComputationalRadiationPhysics/isaac/commit/3a09241cc060bb2a60ecbd1a0ebcacbd2d55d16e)

**Comment by ax3l** [comment]
> I really wonder, what is so hard on defining

Well, CUDA 9 RC2 is already `__CUDACC_VER_BUILD__` > 100...

**Comment by ax3l** [comment]
Your fix does not fix it. see inline comment within.

**Comment by theZiz** [comment]
Ups...

**Comment by theZiz** [comment]
> Well, CUDA 9 RC2 is already __CUDACC_VER_BUILD__ > 100...

Ah. Bad.

**Comment by theZiz** [comment]
Fixed? https://github.com/ComputationalRadiationPhysics/isaac/commit/1702a760773ae1a9dd3d410a5ae86e58de6f1973

**Comment by ax3l** [comment]
dunno, did you test the variables? :)

Btw., your `INSTALL.md` does officially support CUDA 7.0.
But in CUDA 7.0 these vars did all not yet exist at all. https://gist.github.com/ax3l/9489132

**Comment by theZiz** [comment]
I tested the values, yes.
However, your second information makes the whole test useless as it is. So if I understand http://developer.download.nvidia.com/compute/cuda/7.5/Prod/docs/sidebar/CUDA_Toolkit_Release_Notes.pdf correctly, just checking whether `__CUDACC_VER_MAJOR__` and/or `__CUDACC_VER_MINOR__` are not defined, should be sufficient.

**Comment by ax3l** [comment]
Indeed yes. If you only support CUDA 7.0+ and want to find out if you are CUDA 7.0, than check if `__CUDACC_VER_MAJOR__` is *not defined*.

**Comment by ax3l** [comment]
See also this boost issue: https://github.com/boostorg/config/pull/175

**Comment by theZiz** [comment]
[Fixed](https://github.com/ComputationalRadiationPhysics/isaac/commit/8b572470890bcdd20ba7db0d6113de2da7503bf1)¿

**Comment by ax3l** [comment]
Sure, if you also add `defined(__CUDACC__) &&` because you only want to add this work-around for your CUDA backend...

But who am I to judge (or test)...

**Comment by ax3l** [comment]
Also, you can set such defines in your CMake files to make them include order independent...
