### ISSUE TITLE
CUDA Startup: Jitify

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#71]
In order to prevent NxN pre-compiles of functor chains and long startups on CUDA architectures, NVRTC is an option we long thought about.

I just found this library from Nvidia, [jitify](https://github.com/NVIDIA/jitify).
It looks like it could significantly easen the process of writing our functor chains in NVRTC. Definitely worth investigating that, maybe as a student project.

**Comment by theZiz** [comment]
Sounds promising, but I think the most interesting part of a student project would be how to implement it in Alpaka or at least a fallback of jit compiling is not available for a back end / environment.

**Comment by theZiz** [comment]
Also related to this issue of alpaka: https://github.com/ComputationalRadiationPhysics/alpaka/issues/208

**Comment by ax3l** [comment]
true, related to #24

**Comment by ax3l** [comment]
I added it therein and close this duplicate issue
