### ISSUE TITLE
Boost 1.65.0+ Support

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#72]
The include in `isaac.hpp` of [`<boost/config/select_compiler_config.hpp>`](https://github.com/ComputationalRadiationPhysics/isaac/blob/v1.3.2/lib/isaac.hpp#L25) is gone in Boost 1.65.0+.

The only allowed include is defined as [`#include <boost/config.hpp>`](http://www.boost.org/doc/libs/1_65_1/libs/config/doc/html/index.html#boost_config.configuring_boost_for_your_platform.the__boost_config_hpp__header).

http://www.boost.org/doc/libs/1_65_1/boost/config/

Affects isaac up to the latest release, 1.3.2

**Comment by theZiz** [comment]
I have no idea, why I included this file two years ago. Let's remove the `#include` and see, what's happening. :blush: 

What could possibly go wrong?

**Comment by ax3l** [comment]
That's likely because your boost `BOOST_RESULT_OF_USE_TR1` work-around  is not properly added as a CMake define but via the header file. You should move it to CMake as we do it with Boost work-arounds in PMacc: https://github.com/ComputationalRadiationPhysics/picongpu/blob/8e457482f05869423e210a09e825617fba5e18bc/include/pmacc/PMaccConfig.cmake#L272-L323

**Comment by theZiz** [comment]
Could be the case. I will do so. For now [Version 1.3.3](https://github.com/ComputationalRadiationPhysics/isaac/releases/tag/v1.3.3) should work for you.

**Comment by ax3l** [comment]
You could have let me test `dev` first, but sure will test

**Comment by theZiz** [comment]
This was an option? O_o

**Comment by ax3l** [comment]
also, the tag is not on `master` but on a `dev` commit....

**Comment by theZiz** [comment]
Yeah, noticed it, too. Is this a problem?

**Comment by theZiz** [comment]
Well, if you did not use it for some fancy spark magic I can still fix this issue. ;)

**Comment by ax3l** [comment]
you are lucky, just fast-forward your `dev` onto your `master`

**Comment by theZiz** [comment]
Well, I did this already. And forgot to push.
Time for week end...

**Comment by ax3l** [comment]
thanks, I am already testing... (but this won't end any time soon)

**Comment by ax3l** [comment]
works now, thanks a lot! :)
