### ISSUE TITLE
plasma.ninja web page does not conect 

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/isaac#79]
@ax3l The web page of the **foil + fft** visualization on `plasma.ninja` does not connect to hypnos:
```
    http://plasma.ninja/isaac/interface_pof_foil.htm
```

It neither connect to `hypnos5` (from the internal network) nor to `localhost` (if port forwarding).
The current `dev` version works fine. 
The web page on your server shows significant differences to the current `dev`.

cc'ing @theZiz and @steindev

**Comment by ax3l** [comment]
the new URL is 
```
http://laser.plasma.ninja/isaac/interface_pof_foil.htm
```

The reason behind this is that ISAAC server does not yet support WSS (and we don't have a proxy running) that would allow us to use https (which all other domains on my webserver do). So I had to introduce that sub-domain for plaintext comms.

I was swamped in meetings the last days and could not check github periodically.

**Comment by PrometheusPi** [comment]
Server works - will close this issue.
