### ISSUE TITLE
Invalid Functor Pipeline Crashes Library

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/isaac#85]
~~Using the `length` functor on particles (and probably some other functors as well) leads to a crash of PIConGPU.~~
A not correct pipeline according to the ally synatx (missing pipe `|` or similar) causes a crash of the parser in PIConGPU. 

This should be avoided by sending back a warning and not visualizing the quantity.

**Comment by ax3l** [comment]
@FelixTUD this is probably your expertise

**Comment by PrometheusPi** [comment]
@FelixTUD wrote by mail: particles are by default vectors of memntum for the visualizer wich only take the x component. If the functor `length` is applied - the length of the momentum is taken. 
```
length | mul(2)
```
However, missing the pipe `|` or adding parenthesis to length causes a crash in the parser.

**Comment by FelixTUD** [comment]
Will be fixed with the particle integration in pull request #88

**Comment by FelixTUD** [comment]
#88 is merged and issue is resolved, can be closed
