### ISSUE TITLE
libjpeg_turbo questions

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/isaac#93]
@FelixTUD The script you gave me a while ago in March for installing all isaac dependencies works fine on hemera **but** I have to questions:

**1.)** You added your local `libjpeg-turbo` to the `CMAKE_PREFIX_PATH` but set `-DISAAC_JPEG=OFF`- doesn't that make setting the cmake path beforehand obsolete?

**2.)** From the code, I see an explicit warning that isaac should be installed with libjpeg. What are the drawbacks and why could we/you set `-DISAAC_JPEG=OFF`?

**3.)** How did you install `libjpeg-turbo`?

**Comment by PrometheusPi** [comment]
Regarding question **3.)** @psychocoderHPC suggested the following solution:

assuming `~/src`, `~/lib`, and `~/build` exist:
```bash
cd ~/src
git clone git@github.com:libjpeg-turbo/libjpeg-turbo.git
cd ~/build
cmake -DCMAKE_INSTALL_PREFIX=~/lib/libjpeg-turbo -DWITH_SIMD=OFF ../libjpeg-turbo/
# WITH_SIMD=OFF avoids using the `nasm` on hemera.  
make install
```

**Comment by ax3l** [comment]
What's the problem with nasm/simd compiles on Hemera? Will definitely cost performance/latency if this is disabled.

**Comment by PrometheusPi** [comment]
Building the isaac server without libjpeg allows that the simulation at least runs - with libjpeg enabled the simulation does not start. Both do not show any images.

**Comment by PrometheusPi** [comment]
Seems to be an issue with the version of `libwebsockets`. See https://github.com/ComputationalRadiationPhysics/picongpu/pull/2940

**Comment by PrometheusPi** [comment]
Solven when using libwebsocket **2.1-stable** or **2.2-stable**

**Comment by ax3l** [comment]
@PrometheusPi can you please open a new issue, about adding support for newer versions of `libwebsockets`?
In the meantime, please let us update the docs of ISAAC to narrow down the currently supported versions of `libwebsockets`.
